#!/usr/bin/env bash
#
# Installs GLM Studio into the current user's desktop environment: an app
# launcher entry, hicolor icons at every size, and a `glm-studio` launcher on
# PATH. Everything lands under $HOME, so no root is required.
#
# Usage:  bash scripts/install-desktop.sh [--system]
#         --system installs into /usr/local + /usr/share (needs sudo)

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCOPE="user"
[[ "${1:-}" == "--system" ]] && SCOPE="system"

if [[ "$SCOPE" == "system" ]]; then
  PREFIX="/usr/local"
  DATA_DIR="/usr/share"
else
  PREFIX="${HOME}/.local"
  DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}"
fi

BIN_DIR="${PREFIX}/bin"
APPS_DIR="${DATA_DIR}/applications"
ICONS_DIR="${DATA_DIR}/icons/hicolor"

echo "==> Installing GLM Studio (${SCOPE} scope)"
echo "    repo:      ${REPO_DIR}"
echo "    launcher:  ${BIN_DIR}/glm-studio"
echo "    desktop:   ${APPS_DIR}/glm-studio.desktop"

if [[ ! -d "${REPO_DIR}/dist" ]]; then
  echo "!! dist/ is missing. Run 'npm run build' first." >&2
  exit 1
fi

if [[ ! -f "${REPO_DIR}/resources/icons/512x512.png" ]]; then
  echo "==> Generating icons"
  (cd "$REPO_DIR" && node scripts/gen-icons.mjs)
fi

mkdir -p "$BIN_DIR" "$APPS_DIR"

# --- launcher -------------------------------------------------------------
# Prefer a packaged binary from `npm run dist` when one exists; otherwise run
# the checkout through the local Electron.
cat > "${BIN_DIR}/glm-studio" <<LAUNCHER
#!/usr/bin/env bash
# Generated by scripts/install-desktop.sh — regenerate rather than edit.
set -euo pipefail
REPO_DIR="${REPO_DIR}"

packaged="\$(find "\${REPO_DIR}/release" -maxdepth 1 -name '*.AppImage' -print -quit 2>/dev/null || true)"
if [[ -n "\$packaged" && -x "\$packaged" ]]; then
  exec "\$packaged" "\$@"
fi

cd "\$REPO_DIR"
ELECTRON_BIN="\$(node -p "require('electron')" 2>/dev/null || true)"
if [[ -z "\$ELECTRON_BIN" || ! -x "\$ELECTRON_BIN" ]]; then
  echo "GLM Studio: Electron is not installed. Run 'npm install' in \$REPO_DIR." >&2
  exit 1
fi
exec "\$ELECTRON_BIN" "\$REPO_DIR" "\$@"
LAUNCHER
chmod +x "${BIN_DIR}/glm-studio"

# --- icons ----------------------------------------------------------------
for size in 16 24 32 48 64 128 256 512; do
  target="${ICONS_DIR}/${size}x${size}/apps"
  mkdir -p "$target"
  install -m 0644 "${REPO_DIR}/resources/icons/${size}x${size}.png" "${target}/glm-studio.png"
done
mkdir -p "${ICONS_DIR}/scalable/apps"
install -m 0644 "${REPO_DIR}/resources/icon.svg" "${ICONS_DIR}/scalable/apps/glm-studio.svg"

# --- desktop entry --------------------------------------------------------
sed "s|@EXEC@|${BIN_DIR}/glm-studio|g" \
  "${REPO_DIR}/resources/glm-studio.desktop.in" > "${APPS_DIR}/glm-studio.desktop"
chmod 0644 "${APPS_DIR}/glm-studio.desktop"

# --- refresh caches (all optional) ---------------------------------------
command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$APPS_DIR" || true
command -v gtk-update-icon-cache  >/dev/null 2>&1 && gtk-update-icon-cache -f -t "$ICONS_DIR" >/dev/null 2>&1 || true
command -v xdg-desktop-menu       >/dev/null 2>&1 && xdg-desktop-menu forceupdate >/dev/null 2>&1 || true

echo
echo "==> Done. 'GLM Studio' should now appear in your application launcher."
if [[ ":$PATH:" != *":${BIN_DIR}:"* ]]; then
  echo "    Note: ${BIN_DIR} is not on your PATH; add it to launch from a shell."
fi
