import { readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import type { Conversation, ConversationSummary, ProviderId, Transport } from '@shared/types';
import { CONVERSATIONS_DIR } from './paths';
import { createLogger } from '../util/logger';

const log = createLogger('conversations');

/**
 * One JSON file per conversation. Transcripts are small and the count is in the
 * hundreds, so a directory beats a database: it is trivially greppable,
 * backup-friendly, and survives a corrupted single file without losing the rest.
 */

function fileFor(id: string): string {
  // Ids are generated by randomUUID, but a hand-edited request must not be able
  // to escape the directory.
  const safe = id.replace(/[^a-zA-Z0-9-]/g, '');
  if (!safe) throw new Error('invalid conversation id');
  return path.join(CONVERSATIONS_DIR, `${safe}.json`);
}

export function createConversation(input: {
  provider: ProviderId;
  model: string;
  transport: Transport;
  cwd?: string;
  title?: string;
}): Conversation {
  const now = Date.now();
  const conversation: Conversation = {
    id: randomUUID(),
    title: input.title ?? 'New chat',
    provider: input.provider,
    model: input.model,
    transport: input.transport,
    messages: [],
    createdAt: now,
    updatedAt: now,
    cwd: input.cwd,
  };
  saveConversation(conversation);
  return conversation;
}

export function saveConversation(conversation: Conversation): Conversation {
  const next = { ...conversation, updatedAt: Date.now() };
  writeFileSync(fileFor(next.id), JSON.stringify(next, null, 2), { mode: 0o600 });
  return next;
}

export function getConversation(id: string): Conversation | null {
  try {
    return JSON.parse(readFileSync(fileFor(id), 'utf8')) as Conversation;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      log.warn(`conversation ${id} unreadable`, err);
    }
    return null;
  }
}

export function deleteConversation(id: string): void {
  rmSync(fileFor(id), { force: true });
}

export function listConversations(): ConversationSummary[] {
  let files: string[];
  try {
    files = readdirSync(CONVERSATIONS_DIR).filter((f) => f.endsWith('.json'));
  } catch {
    return [];
  }

  const summaries: ConversationSummary[] = [];
  for (const file of files) {
    try {
      const raw = JSON.parse(
        readFileSync(path.join(CONVERSATIONS_DIR, file), 'utf8'),
      ) as Conversation;
      summaries.push({
        id: raw.id,
        title: raw.title,
        provider: raw.provider,
        model: raw.model,
        updatedAt: raw.updatedAt,
        messageCount: raw.messages?.length ?? 0,
      });
    } catch {
      // Skip a corrupt file rather than failing the whole list.
      log.warn(`skipping unreadable conversation file ${file}`);
    }
  }
  return summaries.sort((a, b) => b.updatedAt - a.updatedAt);
}

/** Derives a short title from the first user message. */
export function deriveTitle(text: string): string {
  const cleaned = text
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  if (!cleaned) return 'New chat';
  return cleaned.length > 48 ? `${cleaned.slice(0, 47)}…` : cleaned;
}

/** Renders a transcript as Markdown for the export action. */
export function toMarkdown(conversation: Conversation): string {
  const lines: string[] = [
    `# ${conversation.title}`,
    '',
    `- Provider: ${conversation.provider}`,
    `- Model: ${conversation.model}`,
    `- Transport: ${conversation.transport}`,
    `- Started: ${new Date(conversation.createdAt).toISOString()}`,
    '',
  ];
  for (const message of conversation.messages) {
    lines.push(`## ${message.role}`, '');
    if (message.reasoning) {
      lines.push('<details><summary>Reasoning</summary>', '', message.reasoning, '', '</details>', '');
    }
    lines.push(message.content, '');
  }
  return lines.join('\n');
}
